version: "2"
services:
  website:
    image: 'ghost:0.11.11'
    environment:
      PUBLIC_URL: 'http://192.168.99.100'
      NODE_ENV : 'production'
    ports:
      - '777:2368'
    volumes:
      - ./ghost/blog:/var/lib/ghost
    user: "node"

#docker-compose up