website:
  image: 'ghost:0.11.11'
  restart: always
  environment:
    PUBLIC_URL: 'http://localhost'
    NODE_ENV : 'production'
  ports:
    - '80:2368'
  volumes:
    - ./ghost/blog:/var/lib/ghost


#docker-compose up